package com.example.solochef.model

/**
 * 默认食材库 — 从生鲜电商商品分类映射表生成，51个商品大类
 */
object DefaultIngredients {

    fun load(): IngredientLibrary {
        var ci = 0
        var ii = 0
        fun nc() = "cat_${ci++}"
        fun ni() = "ing_${ii++}"

        return IngredientLibrary(categories = buildList {

            add(IngredientCategory(id = nc(), name = "猪肉", targetCategory = "meat", emoji = "🐷", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "五花肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪前腿肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪后腿肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "里脊肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "梅花肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "大排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙骨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "汤骨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪蹄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪肘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪尾巴", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪耳朵", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪肚", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪心", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪肝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪腰", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪舌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪血", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪板油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肉馅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肉丝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肉片", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑猪肉", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "牛肉", targetCategory = "meat", emoji = "🐂", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "牛腩", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛腱子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛里脊", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛外脊", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛眼肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "上脑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肩肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛臀肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛腿肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛尾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛蹄筋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛百叶", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肚", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛舌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛心", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛骨髓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肥牛卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肉馅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肉丝/片", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "澳洲和牛", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "安格斯牛肉", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "羊肉", targetCategory = "meat", emoji = "🐑", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "羊腿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊腩", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊颈肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊里脊", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊蝎子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊杂", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊肉卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊肉串", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "滩羊肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草原羊肉", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "禽肉", targetCategory = "meat", emoji = "🐔", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "整鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡胸肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡腿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡翅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡爪", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡胗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡心", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡肝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡架", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡块", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄油母鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "老母鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "童子鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "整鸭", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭腿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭翅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭掌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭脖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭头", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭胗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭血", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭舌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹅肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "乳鸽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹌鹑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火鸡腿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡胸肉丁", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "禽蛋", targetCategory = "meat", emoji = "🥚", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "土鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "初生蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "绿壳鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "富硒鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "可生食鸡蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸭蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "咸鸭蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "皮蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹌鹑蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹅蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸽子蛋", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "加工肉制品", targetCategory = "meat", emoji = "🥓", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "培根", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火腿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腊肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腊排骨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腊鸭", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腊鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酱牛肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤猪蹄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火腿肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "脆皮肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "烤肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "台湾香肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡胸肉火腿", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "活鲜/冰鲜水产-鱼类", targetCategory = "meat", emoji = "🐟", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "鲈鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "桂鱼/鳜鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲫鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲤鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鳊鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲢鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄骨鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "罗非鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "泥鳅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鳝鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "多宝鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鳕鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "三文鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "金枪鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "带鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲳鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "比目鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "秋刀鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "马鲛鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "多春鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沙丁鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "巴沙鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙利鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鳗鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "石斑鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "笋壳鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鮰鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱿鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "章鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "墨鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "三去鱼类", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "活鲜/冰鲜水产-虾蟹类", targetCategory = "meat", emoji = "🦐", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "基围虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "斑节虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小河虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "罗氏沼虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "北极虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "阿根廷红虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "皮皮虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "大闸蟹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "梭子蟹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "帝王蟹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "面包蟹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花蟹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "大闸蟹蟹黄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾仁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾滑", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "活鲜/冰鲜水产-贝类", targetCategory = "meat", emoji = "🐚", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "花蛤", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "文蛤", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蛤蜊", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蛏子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "扇贝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "生蚝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲍鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海螺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花螺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "象拔蚌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "青口贝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "北极贝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "带子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲍鱼仔", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "田螺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "钉螺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "毛蚶", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "血蛤", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水产干货", targetCategory = "meat", emoji = "🦑", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "海带", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "紫菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干贝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海蜇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干海参", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干鲍鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼肚", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "烤鱼片", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干银鱼", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "冷冻水产", targetCategory = "meat", emoji = "🧊", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "冷冻虾仁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻巴沙鱼柳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻鳕鱼块", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻三文鱼排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻鱿鱼圈", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻什锦海鲜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻蟹棒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻鱼丸/虾丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻贝柱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻带鱼段", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻黄花鱼", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "速冻-火锅肉丸类", targetCategory = "meat", emoji = "🍢", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "撒尿牛丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肉丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "墨鱼丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蟹棒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙虾丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛筋丸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肥牛卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊肉卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "乌鸡卷", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "速冻-火锅肉片类", targetCategory = "meat", emoji = "🥩", isCustom = false, ingredients = listOf(
            )))

            add(IngredientCategory(id = nc(), name = "腌制肉类", targetCategory = "meat", emoji = "🍖", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "腌制牛排", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "奥尔良鸡翅", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "叶菜类", targetCategory = "vegetable", emoji = "🥬", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "菠菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "生菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "油麦菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茼蒿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芹菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "空心菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "苋菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "韭菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茴香", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "荠菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "紫苏", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "薄荷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芝麻菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羽衣甘蓝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "马齿苋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "木耳菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红薯叶", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "穿心莲", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冰草", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "罗勒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "迷迭香", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "莳萝", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "白菜类", targetCategory = "vegetable", emoji = "🥬", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "大白菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小白菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "娃娃菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "奶白菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡毛菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "乌塌菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菜心", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菜薹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红菜薹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "快菜", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "甘蓝类", targetCategory = "vegetable", emoji = "🥦", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "卷心菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "紫甘蓝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "西兰花", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "有机花菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "宝塔菜花", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芥蓝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "苤蓝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "抱子甘蓝", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "根菜类", targetCategory = "vegetable", emoji = "🥕", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "白萝卜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "胡萝卜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "青萝卜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "樱桃萝卜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "水萝卜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红菜头", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛蒡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芜菁", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "薯芋类", targetCategory = "vegetable", emoji = "🥔", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "土豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红薯", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "紫薯", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "山药", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芋头", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "生姜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "洋姜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "魔芋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "凉薯", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "雪莲果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "木薯", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "葱蒜类", targetCategory = "vegetable", emoji = "🧅", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "大葱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小葱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "洋葱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "大蒜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒜苗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒜薹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒜黄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "韭葱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "藠头", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "茄果类", targetCategory = "vegetable", emoji = "🍅", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "番茄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茄子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "辣椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "青椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "彩椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小米椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "二荆条", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "美人椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "薄皮椒", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "瓜类", targetCategory = "vegetable", emoji = "🥒", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "黄瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冬瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "南瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "西葫芦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "丝瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "苦瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "瓠瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "节瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "佛手瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "金丝瓜", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "豆类", targetCategory = "vegetable", emoji = "🫘", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "四季豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豇豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "毛豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豌豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蚕豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "扁豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "荷兰豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "甜豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "油豆角", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "刀豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "四棱豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆芽", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "菌菇类", targetCategory = "vegetable", emoji = "🍄", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "香菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "金针菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "杏鲍菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "平菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蟹味菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茶树菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "口蘑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡腿菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "秀珍菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑木耳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "银耳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "竹荪", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猴头菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "松茸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡枞菌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肝菌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "羊肚菌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虫草花", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹿茸菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "滑子菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪肚菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "榛蘑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "舞茸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "姬松茸", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "绣球菌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑牛肝菌", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水生蔬菜", targetCategory = "vegetable", emoji = "🪷", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "莲藕", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茭白", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "慈姑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "荸荠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菱角", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "水芹菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "莼菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芡实", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒲菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆瓣菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜海带", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜裙带菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙须菜", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "芽苗菜", targetCategory = "vegetable", emoji = "🌱", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "绿豆芽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄豆芽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑豆芽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豌豆苗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花生芽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "萝卜苗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香椿苗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "苜蓿芽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "松柳苗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小麦苗", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "多年生及杂类", targetCategory = "vegetable", emoji = "🌽", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "竹笋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芦笋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "百合", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香椿", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枸杞叶", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "秋葵", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄花菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "玉米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蕨菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼腥草", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枸杞", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜黄花菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "莲子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草芽", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "净菜/沙拉菜", targetCategory = "vegetable", emoji = "🥗", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "混合沙拉菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "即食蔬菜沙拉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "免洗切配蔬菜包", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "去皮切块净菜组合", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-浆果类", targetCategory = "vegetable", emoji = "🍓", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "草莓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蓝莓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "树莓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑莓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "桑葚", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "葡萄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猕猴桃", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "柿子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "无花果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑加仑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "灯笼果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "石榴", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "百香果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "圣女果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "杨梅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蔓越莓", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-柑橘类", targetCategory = "vegetable", emoji = "🍊", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "蜜橘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "砂糖橘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沃柑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "耙耙柑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "丑橘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "茂谷柑", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "金桔", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "甜橙", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "柚子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "葡萄柚", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "柠檬", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "青金桔", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "佛手", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-核果类", targetCategory = "vegetable", emoji = "🍑", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "桃", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "李", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "杏", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "樱桃", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "车厘子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枣", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "杨梅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "青梅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "荔枝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "龙眼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红毛丹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枇杷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "橄榄", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-仁果类", targetCategory = "vegetable", emoji = "🍎", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "苹果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "梨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "山楂", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枇杷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海棠果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沙果", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-瓜果类", targetCategory = "vegetable", emoji = "🍈", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "西瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "哈密瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "甜瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄河蜜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "玫珑蜜瓜", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-热带水果", targetCategory = "vegetable", emoji = "🥭", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "芒果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "榴莲", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菠萝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菠萝蜜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香蕉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "木瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "山竹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "莲雾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛油果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "释迦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "杨桃", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "番石榴", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "椰子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "甘蔗", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火龙果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酸角", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "人心果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡蛋果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蛇皮果", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-进口特色", targetCategory = "vegetable", emoji = "🍇", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "车厘子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蓝莓", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛油果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "榴莲", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "山竹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "帝王椰", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "新西兰奇异果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "澳洲柑橘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "南非西柚", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "水果-果切/鲜果制品", targetCategory = "vegetable", emoji = "🍉", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "果切拼盘", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜切西瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜切哈密瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜切菠萝蜜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜榨果汁", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "速冻-冷冻蔬菜", targetCategory = "vegetable", emoji = "🥶", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "冷冻玉米粒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻豌豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻蔬菜混合", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻毛豆", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "基础调味品", targetCategory = "seasoning", emoji = "🧂", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "食盐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白砂糖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冰糖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红糖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "绵白糖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "方糖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "糖霜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "味精", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鸡精", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "淀粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酵母", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "泡打粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小苏打", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "食用碱", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "酱油类", targetCategory = "seasoning", emoji = "🫙", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "生抽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "老抽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "味极鲜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒸鱼豉油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海鲜酱油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红烧酱油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "儿童酱油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄豆酱油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "日式酱油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼露", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "醋类", targetCategory = "seasoning", emoji = "🫗", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "陈醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "米醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "苹果醋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑醋", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "料酒/烹饪用酒", targetCategory = "seasoning", emoji = "🍶", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "料酒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄酒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "啤酒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白酒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "米酒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红酒", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "食用油", targetCategory = "seasoning", emoji = "🫒", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "花生油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "菜籽油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "大豆油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "玉米油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "葵花籽油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "橄榄油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "山茶油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芝麻油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "核桃油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "亚麻籽油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "稻米油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "椰子油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "猪油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "植物调和油", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "蚝油/酱料类", targetCategory = "seasoning", emoji = "🥫", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "蚝油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄豆酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆瓣酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "甜面酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "番茄酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "番茄膏", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沙茶酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "XO酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "柱侯酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海鲜酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "叉烧酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "排骨酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "拌饭酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花生酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芝麻酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沙拉酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "油醋汁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "虾酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腐乳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆豉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "橄榄菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "剁椒酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "老干妈", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "辣椒类调味品", targetCategory = "seasoning", emoji = "🌶️", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "辣椒面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干辣椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "辣椒酱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "辣椒油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花椒油", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花椒粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "麻椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "泡椒", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "香辛料", targetCategory = "seasoning", emoji = "🌿", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "八角", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "桂皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "香叶", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "丁香", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "草果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白芷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肉蔻", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "砂仁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小茴香", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "陈皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "孜然", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑胡椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白胡椒", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "五香粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "十三香", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "咖喱", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "姜粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蒜粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芥末", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "肉桂粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆蔻粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "迷迭香", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "火锅底料/复合调味", targetCategory = "seasoning", emoji = "🍲", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "火锅底料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火锅蘸料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "麻辣香锅料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "水煮鱼料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酸菜鱼调料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "麻婆豆腐料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼香肉丝料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "宫保鸡丁料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "回锅肉调料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小龙虾调料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤料包", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红烧料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄焖鸡酱料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "钵钵鸡调料", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷锅串串料", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "豆制品", targetCategory = "seasoning", emoji = "🫘", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "嫩豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "中豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "老豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冻豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "日本豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "千页豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆腐干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆腐皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腐竹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆腐丝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "素鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "油豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "面筋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆腐乳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆皮结", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "素肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆浆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆花", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "炸豆腐丸子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "臭豆腐", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "豆渣", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "米面杂粮", targetCategory = "seasoning", emoji = "🌾", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "大米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "面粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "挂面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "方便面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "米粉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "意大利面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "紫米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "糯米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "糙米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "薏仁米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "燕麦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "玉米面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "荞麦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "绿豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黑豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芸豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鹰嘴豆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "藜麦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "八宝粥米", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "奇亚籽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "亚麻籽", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鲜面条", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "饺子皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "年糕", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "馒头", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "包子", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "速冻-面点主食", targetCategory = "seasoning", emoji = "🥟", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "速冻水饺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻馄饨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻汤圆", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻小笼包", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻烧麦", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻春卷", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻粽子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "速冻包子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "手抓饼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "葱油饼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "蛋挞皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "披萨", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冷冻薯条", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "冰淇淋", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "预制菜/熟食", targetCategory = "seasoning", emoji = "🍱", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "酸菜鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "水煮牛肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "糖醋里脊", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "宫保鸡丁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "鱼香肉丝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "回锅肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红烧肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "毛血旺", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "烤鱼", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "小龙虾", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "佛跳墙", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "咖喱鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "黄焖鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "牛肉面", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "自热火锅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "煲仔饭", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤牛肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤猪蹄", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤鸡爪", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤鸭脖", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤鸭翅", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤鸭舌", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "卤蛋", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "盐水鸭", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "白切鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "烤鸡", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "烤鸭", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酱牛肉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "凉皮", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "凉拌菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "寿司", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "沙拉", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "三明治", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "饭团", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "即食汤品", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "即食粥", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "料理包", categoryId = "", isStandard = true),
            )))

            add(IngredientCategory(id = nc(), name = "腌菜/罐头/干货", targetCategory = "seasoning", emoji = "🥒", isCustom = false, ingredients = listOf(
                IngredientItem(id = ni(), name = "榨菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酸菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "泡菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "萝卜干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "雪菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "梅干菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酸豆角", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "酱黄瓜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "糖蒜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "罐头", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "火腿肠", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干木耳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干银耳", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干黄花菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干腐竹", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "粉丝", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干紫菜", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "海苔", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "笋干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干茶树菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "干花菇", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "红枣", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "桂圆干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "枸杞", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "葡萄干", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "核桃仁", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "腰果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "巴旦木", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "开心果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "夏威夷果", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "松子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "榛子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "瓜子", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "花生", categoryId = "", isStandard = true),
                IngredientItem(id = ni(), name = "芝麻", categoryId = "", isStandard = true),
            )))

        })
    }
}
